name: Build and Deploy to Server
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  persist-credentials: false
            - name: Setup node
              uses: actions/setup-node@v7
              with:
                  node-version: 24
            - name: Setup pnpm
              uses: pnpm/action-setup@v6
            - name: Build
              run: |
                  node -v
                  npm -v
                  pnpm -v
                  pnpm install
                  pnpm run build:production
                  cd www
                  zip -qr ionic.zip *
            - name: Dist
              run: |
                  cd www
                  zip -qr ionic.zip *
            - name: Deploy
              uses: wlixcc/SFTP-Deploy-Action@v1.2.6
              with:
                  username: ${{ secrets.SERVER_USER }}
                  server: ${{ secrets.SERVER_HOST }}
                  ssh_private_key: ${{ secrets.SERVER_KEY }}
                  local_path: './www/ionic.zip'
                  remote_path: '/data/deploy'
                  sftpArgs: '-o ConnectTimeout=5'
